# Generated by Django 6.0.5 on 2026-06-09 13:24
# pylint: skip-file

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('exigencia_nrc', '0001_initial'),
        ('ingrediente', '0001_initial'),
        ('lote', '0003_remove_lote_idade_alter_lote_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('objetivo_otimizacao', models.CharField(choices=[('CUSTO', 'Mínimo custo'), ('PB', 'Máxima proteína bruta'), ('FDN', 'Mínimo FDN')], max_length=5, verbose_name='Objetivo de otimização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('vol_ms_percent', models.FloatField(blank=True, null=True, verbose_name='Volumoso % MS')),
                ('conc_ms_percent', models.FloatField(blank=True, null=True, verbose_name='Concentrado % MS')),
                ('mistura_conc', models.FloatField(blank=True, null=True, verbose_name='Mistura concentrado (kg MS/dia)')),
                ('rs_kg_mn_total', models.FloatField(blank=True, null=True, verbose_name='Total MN (kg/animal/dia)')),
                ('custo_animal_dia', models.FloatField(blank=True, null=True, verbose_name='Custo animal/dia (R$)')),
                ('custo_lote_dia', models.FloatField(blank=True, null=True, verbose_name='Custo lote/dia (R$)')),
                ('dt_inc', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('dt_alt', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('exigencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulacoes', to='exigencia_nrc.exigencianrc', verbose_name='Exigência NRC')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulacoes', to='lote.lote', verbose_name='Lote')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulacoes', to='accounts.usuario', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Formulação',
                'verbose_name_plural': 'Formulações',
                'ordering': ['-dt_inc'],
            },
        ),
        migrations.CreateModel(
            name='CustoViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_entrada', models.FloatField(verbose_name='Peso entrada (kg)')),
                ('peso_saida_estimado', models.FloatField(verbose_name='Peso saída estimado (kg)')),
                ('num_animais', models.PositiveIntegerField(verbose_name='Nº animais')),
                ('gmd', models.FloatField(verbose_name='GMD (kg/dia)')),
                ('estimativa_permanencia', models.PositiveIntegerField(verbose_name='Permanência estimada (dias)')),
                ('cms', models.FloatField(verbose_name='CMS (kg/dia)')),
                ('perda_alimentos', models.FloatField(default=0.0, verbose_name='Perda de alimentos (%)')),
                ('valor_kg_ovino', models.FloatField(default=0.0, verbose_name='Valor R$/kg PV')),
                ('custo_total_dieta', models.FloatField(verbose_name='Custo total dieta (R$)')),
                ('preco_min_lucro', models.FloatField(default=0.0, verbose_name='Preço mínimo p/ lucro (R$/kg)')),
                ('formulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custo_viabilidade', to='formulacao.formulacao')),
            ],
            options={
                'verbose_name': 'Custo e Viabilidade',
                'verbose_name_plural': 'Custos e Viabilidades',
            },
        ),
        migrations.CreateModel(
            name='AjusteDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_ajustado', models.FloatField(verbose_name='Peso ajustado (kg)')),
                ('cms_percent', models.FloatField(verbose_name='CMS (% PV)')),
                ('lote_un', models.PositiveIntegerField(verbose_name='Animais no lote')),
                ('sobras_percent', models.FloatField(default=5.0, verbose_name='Sobras (%)')),
                ('num_refeicoes', models.PositiveIntegerField(default=2, verbose_name='Nº refeições/dia')),
                ('perda_alimentos', models.FloatField(default=0.0, verbose_name='Perda de alimentos (%)')),
                ('fornecimento_unit', models.FloatField(verbose_name='Fornecimento/animal (kg MN/dia)')),
                ('fornecimento_lote', models.FloatField(verbose_name='Fornecimento/lote (kg MN/dia)')),
                ('formulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ajuste_dieta', to='formulacao.formulacao')),
            ],
            options={
                'verbose_name': 'Ajuste de Dieta',
                'verbose_name_plural': 'Ajustes de Dieta',
            },
        ),
        migrations.CreateModel(
            name='IngredienteFormulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ms_porcent', models.FloatField(verbose_name='Participação % MS')),
                ('ms_kg', models.FloatField(verbose_name='MS kg/animal/dia')),
                ('mn_kg', models.FloatField(verbose_name='MN kg/animal/dia')),
                ('pb_kg', models.FloatField(verbose_name='PB kg/dia')),
                ('ndt_kg', models.FloatField(verbose_name='NDT kg/dia')),
                ('fdn_kg', models.FloatField(verbose_name='FDN kg/dia')),
                ('ee_kg', models.FloatField(verbose_name='EE kg/dia')),
                ('ca_kg', models.FloatField(verbose_name='Ca kg/dia')),
                ('p_kg', models.FloatField(verbose_name='P kg/dia')),
                ('custo_dia', models.FloatField(verbose_name='Custo/dia R$')),
                ('formulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_formulacao', to='formulacao.formulacao')),
                ('ingrediente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes_formulacao', to='ingrediente.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente na Formulação',
                'verbose_name_plural': 'Ingredientes na Formulação',
                'ordering': ['-ms_porcent'],
            },
        ),
        migrations.CreateModel(
            name='MotorOtimizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(choices=[('CUSTO', 'Mínimo custo'), ('PB', 'Máxima proteína bruta'), ('FDN', 'Mínimo FDN')], max_length=5)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('inviavel', 'Inviável')], max_length=10)),
                ('motivo_inviabilidade', models.TextField(blank=True, null=True)),
                ('custo_otimizado', models.FloatField(blank=True, null=True)),
                ('restricoes_aplicadas', models.JSONField(blank=True, default=list)),
                ('resultado_simplex', models.JSONField(blank=True, default=dict)),
                ('dt_execucao', models.DateTimeField(auto_now_add=True)),
                ('formulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motor_otimizacao', to='formulacao.formulacao')),
            ],
            options={
                'verbose_name': 'Motor de Otimização',
                'verbose_name_plural': 'Motores de Otimização',
            },
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(choices=[('CUSTO', 'Mínimo custo'), ('PB', 'Máxima proteína bruta'), ('FDN', 'Mínimo FDN')], max_length=5)),
                ('score', models.FloatField(default=0.0)),
                ('delta_custo', models.FloatField(default=0.0)),
                ('delta_pb', models.FloatField(default=0.0)),
                ('delta_ndt', models.FloatField(default=0.0)),
                ('distancia_euclidiana', models.FloatField(default=0.0)),
                ('dt_geracao', models.DateField(auto_now_add=True)),
                ('formulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='formulacao.formulacao')),
                ('ingrediente_substituido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituido_em', to='ingrediente.ingrediente')),
                ('ingrediente_sugerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugerido_em', to='ingrediente.ingrediente')),
            ],
            options={
                'verbose_name': 'Recomendação',
                'verbose_name_plural': 'Recomendações',
                'ordering': ['-score'],
            },
        ),
        migrations.AddIndex(
            model_name='formulacao',
            index=models.Index(fields=['lote', '-dt_inc'], name='formulacao__lote_id_481a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='formulacao',
            index=models.Index(fields=['usuario', '-dt_inc'], name='formulacao__usuario_f74489_idx'),
        ),
    ]
