# Generated by Django 6.0.5 on 2026-06-21 00:00
# pylint: skip-file

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('exigencia_nrc', '0001_initial'),
        ('formulacao', '0001_initial'),
        ('ingrediente', '0001_initial'),
        ('lote', '0003_remove_lote_idade_alter_lote_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutriente', models.CharField(blank=True, choices=[('PB', 'PB'), ('NDT', 'NDT'), ('FDN', 'FDN'), ('EE', 'EE'), ('CA', 'CA'), ('P', 'P')], db_index=True, help_text='Null para alertas de tipo SOMA (não associados a nutriente específico).', max_length=10, null=True, verbose_name='Nutriente')),
                ('tipo', models.CharField(choices=[('DEFICIT', 'Déficit'), ('EXCESSO', 'Excesso'), ('SOMA', 'Soma de participações fora de 100%')], max_length=10, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('INFO', 'Informação (desvio ≤ 5%)'), ('ATENCAO', 'Atenção (desvio 5–20%)'), ('CRITICO', 'Crítico (desvio > 20%)')], db_index=True, max_length=10, verbose_name='Severidade')),
                ('valor_atual', models.FloatField(verbose_name='Valor atual (% MS)')),
                ('valor_limite', models.FloatField(help_text='O limite (min ou max) que foi ultrapassado.', verbose_name='Valor limite violado (% MS)')),
                ('magnitude_relativa', models.FloatField(default=0.0, help_text='Proporção do desvio em relação ao limite (ex.: 0.20 = 20% fora do limite).', verbose_name='Magnitude relativa')),
                ('snapshot_versao_geracao', models.PositiveIntegerField(verbose_name='Versão em que foi gerado')),
                ('snapshot_versao_resolucao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Versão em que foi resolvido')),
                ('resolvido', models.BooleanField(db_index=True, default=False, verbose_name='Resolvido')),
                ('dt_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('dt_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
            ],
            options={
                'verbose_name': 'Alerta Nutricional',
                'verbose_name_plural': 'Alertas Nutricionais',
                'ordering': ['-dt_geracao', 'severidade'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoNutriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutriente', models.CharField(choices=[('PB', 'PB'), ('NDT', 'NDT'), ('FDN', 'FDN'), ('EE', 'EE'), ('CA', 'CA'), ('P', 'P')], db_index=True, max_length=10, verbose_name='Nutriente')),
                ('operador', models.CharField(choices=[('=', 'Igual (=)'), ('>=', 'Maior ou igual (>=)'), ('<=', 'Menor ou igual (<=)'), ('ENTRE', 'Entre (intervalo)')], max_length=10, verbose_name='Operador')),
                ('valor_min', models.FloatField(blank=True, null=True, verbose_name='Valor mínimo (% MS)')),
                ('valor_max', models.FloatField(blank=True, null=True, verbose_name='Valor máximo (% MS)')),
                ('valor_origem_nrc', models.FloatField(blank=True, help_text='Valor percentual que veio da tabela NRC; preservado para rastreabilidade.', null=True, verbose_name='Valor original NRC (% MS)')),
                ('alterado_pelo_usuario', models.BooleanField(default=False, verbose_name='Alterado pelo usuário')),
                ('dt_alteracao', models.DateTimeField(auto_now=True, verbose_name='Última alteração')),
            ],
            options={
                'verbose_name': 'Configuração de Nutriente',
                'verbose_name_plural': 'Configurações de Nutrientes',
                'ordering': ['nutriente'],
            },
        ),
        migrations.CreateModel(
            name='EventoFormulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Formulação criada'), ('INGREDIENTE_ADICIONADO', 'Ingrediente adicionado'), ('INGREDIENTE_REMOVIDO', 'Ingrediente removido'), ('PARTICIPACAO_EDITADA', 'Participação editada manualmente'), ('PARTICIPACAO_DESTRAVADA', 'Participação destravada'), ('EXIGENCIA_ALTERADA', 'Exigência configurada alterada'), ('RECALCULO_SOLICITADO', 'Recálculo explícito solicitado'), ('REDISTRIBUICAO_EXECUTADA', 'Redistribuição automática executada'), ('VERSAO_RESTAURADA', 'Estado restaurado a partir de snapshot')], db_index=True, max_length=30, verbose_name='Tipo de evento')),
                ('payload', models.JSONField(default=dict, help_text='Contexto específico do evento (ex.: {ingrediente_id: 42, ms_porcent_anterior: 30.0}).', verbose_name='Dados do evento')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Evento de Formulação',
                'verbose_name_plural': 'Eventos de Formulação',
                'ordering': ['formulacao', 'dt_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ExigenciaConfigurada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cms_kg', models.FloatField(help_text='Consumo de Matéria Seca do lote, calculado no momento da criação.', verbose_name='CMS (kg/dia)')),
            ],
            options={
                'verbose_name': 'Exigência Configurada',
                'verbose_name_plural': 'Exigências Configuradas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoConfiguracaoNutriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operador_anterior', models.CharField(choices=[('=', 'Igual (=)'), ('>=', 'Maior ou igual (>=)'), ('<=', 'Menor ou igual (<=)'), ('ENTRE', 'Entre (intervalo)')], max_length=10)),
                ('valor_min_anterior', models.FloatField(blank=True, null=True)),
                ('valor_max_anterior', models.FloatField(blank=True, null=True)),
                ('operador_novo', models.CharField(choices=[('=', 'Igual (=)'), ('>=', 'Maior ou igual (>=)'), ('<=', 'Menor ou igual (<=)'), ('ENTRE', 'Entre (intervalo)')], max_length=10)),
                ('valor_min_novo', models.FloatField(blank=True, null=True)),
                ('valor_max_novo', models.FloatField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data da alteração')),
            ],
            options={
                'verbose_name': 'Histórico de Configuração de Nutriente',
                'verbose_name_plural': 'Históricos de Configurações de Nutrientes',
                'ordering': ['-dt_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotFormulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao_num', models.PositiveIntegerField(help_text='Incrementado por formulacao_id. Unicidade garantida por unique_together.', verbose_name='Número da versão')),
                ('payload', models.JSONField(help_text='JSON auto-contido com: participacoes, resultado_adequacao, alertas, exigencia_configurada, schema_version, dt_criacao, usuario_id, motivo.', verbose_name='Payload (estado completo)')),
                ('motivo', models.CharField(blank=True, default='', help_text="Ex.: 'geração inicial', 'edição manual ms_porcent', 'adição de ingrediente'.", max_length=200, verbose_name='Motivo da versão')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Snapshot de Formulação',
                'verbose_name_plural': 'Snapshots de Formulação',
                'ordering': ['formulacao', 'versao_num'],
            },
        ),
        migrations.RemoveField(
            model_name='ajustedieta',
            name='formulacao',
        ),
        migrations.RemoveField(
            model_name='custoviabilidade',
            name='formulacao',
        ),
        migrations.RemoveField(
            model_name='motorotimizacao',
            name='formulacao',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='formulacao',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='ingrediente_substituido',
        ),
        migrations.RemoveField(
            model_name='recomendacao',
            name='ingrediente_sugerido',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='conc_ms_percent',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='custo_animal_dia',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='custo_lote_dia',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='exigencia',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='mistura_conc',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='objetivo_otimizacao',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='rs_kg_mn_total',
        ),
        migrations.RemoveField(
            model_name='formulacao',
            name='vol_ms_percent',
        ),
        migrations.AlterUniqueTogether(
            name='ingredienteformulacao',
            unique_together={('formulacao', 'ingrediente')},
        ),
        migrations.AddField(
            model_name='formulacao',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ATIVA', 'Ativa'), ('ARQUIVADA', 'Arquivada')], db_index=True, default='RASCUNHO', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='ingredienteformulacao',
            name='origem_participacao',
            field=models.CharField(choices=[('CALCULADA', 'Calculada pelo sistema'), ('MANUAL_TRAVADA', 'Travada pelo usuário')], db_index=True, default='CALCULADA', help_text='CALCULADA = definida/ajustada pelo sistema. MANUAL_TRAVADA = editada pelo usuário; nunca alterada por redistribuição automática.', max_length=15, verbose_name='Origem da participação'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ca_kg',
            field=models.FloatField(default=0.0, verbose_name='Ca (kg/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ee_kg',
            field=models.FloatField(default=0.0, verbose_name='EE (kg/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='fdn_kg',
            field=models.FloatField(default=0.0, verbose_name='FDN (kg/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='formulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_formulacao', to='formulacao.formulacao', verbose_name='Formulação'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ingrediente',
            field=models.ForeignKey(help_text='SET_NULL preserva o registro mesmo se o ingrediente for excluído; o SnapshotFormulacao guarda o vetor nutricional capturado no momento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes_formulacao', to='ingrediente.ingrediente', verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='mn_kg',
            field=models.FloatField(default=0.0, verbose_name='MN (kg/animal/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ms_kg',
            field=models.FloatField(default=0.0, verbose_name='MS (kg/animal/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ms_porcent',
            field=models.FloatField(default=0.0, help_text='Percentual da MS total (0-100). O repositório converte para fração 0-1 no domínio.', verbose_name='Participação % MS'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ndt_kg',
            field=models.FloatField(default=0.0, verbose_name='NDT (kg/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='p_kg',
            field=models.FloatField(default=0.0, verbose_name='P (kg/dia)'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='pb_kg',
            field=models.FloatField(default=0.0, verbose_name='PB (kg/dia)'),
        ),
        migrations.AddIndex(
            model_name='formulacao',
            index=models.Index(fields=['status', '-dt_inc'], name='formulacao__status_eb4e90_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredienteformulacao',
            index=models.Index(fields=['formulacao', 'origem_participacao'], name='formulacao__formula_06abb3_idx'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='formulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='formulacao.formulacao', verbose_name='Formulação'),
        ),
        migrations.AddField(
            model_name='eventoformulacao',
            name='formulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='formulacao.formulacao', verbose_name='Formulação'),
        ),
        migrations.AddField(
            model_name='eventoformulacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_formulacao', to='accounts.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='exigenciaconfigurada',
            name='exigencia_nrc_origem',
            field=models.ForeignKey(blank=True, help_text='Referência read-only à linha NRC usada como ponto de partida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exigencias_configuradas', to='exigencia_nrc.exigencianrc', verbose_name='Exigência NRC de origem'),
        ),
        migrations.AddField(
            model_name='exigenciaconfigurada',
            name='formulacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exigencia_configurada', to='formulacao.formulacao', verbose_name='Formulação'),
        ),
        migrations.AddField(
            model_name='configuracaonutriente',
            name='exigencia_configurada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_nutrientes', to='formulacao.exigenciaconfigurada', verbose_name='Exigência configurada'),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaonutriente',
            name='configuracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='formulacao.configuracaonutriente', verbose_name='Configuração'),
        ),
        migrations.AddField(
            model_name='historicoconfiguracaonutriente',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_configuracoes', to='accounts.usuario', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='snapshotformulacao',
            name='formulacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='formulacao.formulacao', verbose_name='Formulação'),
        ),
        migrations.AddField(
            model_name='snapshotformulacao',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_formulacao', to='accounts.usuario', verbose_name='Usuário'),
        ),
        migrations.DeleteModel(
            name='AjusteDieta',
        ),
        migrations.DeleteModel(
            name='CustoViabilidade',
        ),
        migrations.DeleteModel(
            name='MotorOtimizacao',
        ),
        migrations.DeleteModel(
            name='Recomendacao',
        ),
        migrations.RemoveField(
            model_name='ingredienteformulacao',
            name='custo_dia',
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['formulacao', 'resolvido'], name='formulacao__formula_4794c0_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['formulacao', 'nutriente', 'tipo'], name='formulacao__formula_241e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['formulacao', 'severidade', 'resolvido'], name='formulacao__formula_3d839a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoformulacao',
            index=models.Index(fields=['formulacao', '-dt_criacao'], name='formulacao__formula_9a6680_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoformulacao',
            index=models.Index(fields=['formulacao', 'tipo_evento'], name='formulacao__formula_5d07f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracaonutriente',
            unique_together={('exigencia_configurada', 'nutriente')},
        ),
        migrations.AddIndex(
            model_name='snapshotformulacao',
            index=models.Index(fields=['formulacao', '-versao_num'], name='formulacao__formula_5c30ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='snapshotformulacao',
            unique_together={('formulacao', 'versao_num')},
        ),
    ]
