# Generated by Django 6.0.5 on 2026-06-24 17:22
# pylint: skip-file

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacao', '0002_alerta_configuracaonutriente_eventoformulacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoformulacao',
            name='payload',
            field=models.JSONField(default=dict, help_text='Contexto específico do evento         (ex.: {ingrediente_id: 42, ms_porcent_anterior: 30.0}).', verbose_name='Dados do evento'),
        ),
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='ms_porcent',
            field=models.FloatField(default=0.0, help_text='Percentual da MS total (0-100).         O repositório converte para fração 0-1 no domínio.', verbose_name='Participação % MS'),
        ),
    ]
