# Generated by Django 6.0.5 on 2026-07-06 14:28
# pylint: skip-file

from django.db import migrations, models


def criar_configuracao_ca_p(apps, schema_editor):
    ExigenciaConfigurada = apps.get_model("formulacao", "ExigenciaConfigurada")
    ConfiguracaoNutriente = apps.get_model("formulacao", "ConfiguracaoNutriente")

    para_criar = []
    for exigencia in ExigenciaConfigurada.objects.select_related("exigencia_nrc_origem"):
        if ConfiguracaoNutriente.objects.filter(
            exigencia_configurada=exigencia,
            nutriente="CA_P",
        ).exists():
            continue

        origem = exigencia.exigencia_nrc_origem
        valor = getattr(origem, "ca_p_percentual", None) if origem else None
        if valor is None:
            continue

        para_criar.append(
            ConfiguracaoNutriente(
                exigencia_configurada=exigencia,
                nutriente="CA_P",
                operador="=",
                valor_min=valor,
                valor_max=valor,
                valor_origem_nrc=valor,
                alterado_pelo_usuario=False,
            )
        )

    if para_criar:
        ConfiguracaoNutriente.objects.bulk_create(para_criar)


def remover_configuracao_ca_p(apps, schema_editor):
    ConfiguracaoNutriente = apps.get_model("formulacao", "ConfiguracaoNutriente")
    ConfiguracaoNutriente.objects.filter(nutriente="CA_P").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('formulacao', '0003_alter_eventoformulacao_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='nutriente',
            field=models.CharField(blank=True, choices=[('PB', 'PB'), ('NDT', 'NDT'), ('FDN', 'FDN'), ('EE', 'EE'), ('CA', 'CA'), ('P', 'P'), ('CA_P', 'CA_P')], db_index=True, help_text='Null para alertas de tipo SOMA (não associados a nutriente específico).', max_length=10, null=True, verbose_name='Nutriente'),
        ),
        migrations.AlterField(
            model_name='configuracaonutriente',
            name='nutriente',
            field=models.CharField(choices=[('PB', 'PB'), ('NDT', 'NDT'), ('FDN', 'FDN'), ('EE', 'EE'), ('CA', 'CA'), ('P', 'P'), ('CA_P', 'CA_P')], db_index=True, max_length=10, verbose_name='Nutriente'),
        ),
        migrations.RunPython(criar_configuracao_ca_p, remover_configuracao_ca_p),
    ]
