# Generated by Django 6.0.5 on 2026-07-14 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacao', '0004_alter_alerta_nutriente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='ingrediente_formulacao',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas para alertas do tipo LIMITE_INGREDIENTE: identifica qual ingrediente ultrapassou o limite de participação.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_limite', to='formulacao.ingredienteformulacao', verbose_name='Ingrediente na formulação'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='ingrediente_nome',
            field=models.CharField(blank=True, help_text='Cópia do nome do ingrediente no momento da geração do alerta — preserva a informação mesmo se o ingrediente for removido da formulação.', max_length=200, null=True, verbose_name='Nome do ingrediente (histórico)'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='nutriente',
            field=models.CharField(blank=True, choices=[('PB', 'PB'), ('NDT', 'NDT'), ('FDN', 'FDN'), ('EE', 'EE'), ('CA', 'CA'), ('P', 'P'), ('CA_P', 'CA_P')], db_index=True, help_text='Null para alertas de tipo SOMA ou LIMITE_INGREDIENTE (não associados a nutriente específico).', max_length=10, null=True, verbose_name='Nutriente'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('DEFICIT', 'Déficit'), ('EXCESSO', 'Excesso'), ('SOMA', 'Soma de participações fora de 100%'), ('LIMITE_INGREDIENTE', 'Limite de participação do ingrediente excedido')], max_length=25, verbose_name='Tipo'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['formulacao', 'tipo', 'ingrediente_formulacao'], name='formulacao__formula_5f2f2d_idx'),
        ),
    ]
