# Generated by Django 6.0.5 on 2026-07-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacao', '0005_alerta_ingrediente_formulacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulacao',
            name='custo_animal_dia',
            field=models.FloatField(blank=True, null=True, verbose_name='Custo (R$/animal/dia)'),
        ),
        migrations.AddField(
            model_name='formulacao',
            name='custo_lote_dia',
            field=models.FloatField(blank=True, null=True, verbose_name='Custo (R$/lote/dia)'),
        ),
        migrations.AddField(
            model_name='formulacao',
            name='custo_mn_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Custo (R$/kg MN)'),
        ),
        migrations.AddField(
            model_name='formulacao',
            name='custo_ms_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Custo (R$/kg MS)'),
        ),
        migrations.AddField(
            model_name='ingredienteformulacao',
            name='custo_dia',
            field=models.FloatField(default=0.0, help_text='Calculado pelo MotorCusto via repositório — nunca editado diretamente.', verbose_name='Custo (R$/animal/dia)'),
        ),
        migrations.AddField(
            model_name='ingredienteformulacao',
            name='custo_kg_mn_override',
            field=models.FloatField(blank=True, help_text="Preenchido quando o usuário escolhe 'atualizar preço só nesta receita'. Null = usa o banco de preços regional do usuário (PrecoIngredienteUsuario).", null=True, verbose_name='Custo local (R$/kg MN)'),
        ),
        migrations.AddField(
            model_name='ingredienteformulacao',
            name='origem_custo',
            field=models.CharField(choices=[('CATALOGO', 'Banco de preços do usuário'), ('OVERRIDE_LOCAL', 'Sobrescrito nesta formulação')], default='CATALOGO', max_length=15, verbose_name='Origem do custo'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='tipo',
            field=models.CharField(choices=[('DEFICIT', 'Déficit'), ('EXCESSO', 'Excesso'), ('SOMA', 'Soma de participações fora de 100%'), ('LIMITE_INGREDIENTE', 'Limite de participação do ingrediente excedido'), ('CUSTO_INDISPONIVEL', 'Preço não informado para ao menos um ingrediente')], max_length=25, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='eventoformulacao',
            name='tipo_evento',
            field=models.CharField(choices=[('CRIACAO', 'Formulação criada'), ('INGREDIENTE_ADICIONADO', 'Ingrediente adicionado'), ('INGREDIENTE_REMOVIDO', 'Ingrediente removido'), ('PARTICIPACAO_EDITADA', 'Participação editada manualmente'), ('PARTICIPACAO_DESTRAVADA', 'Participação destravada'), ('EXIGENCIA_ALTERADA', 'Exigência configurada alterada'), ('RECALCULO_SOLICITADO', 'Recálculo explícito solicitado'), ('REDISTRIBUICAO_EXECUTADA', 'Redistribuição automática executada'), ('VERSAO_RESTAURADA', 'Estado restaurado a partir de snapshot'), ('PRECO_ATUALIZADO', 'Preço de ingrediente atualizado')], db_index=True, max_length=30, verbose_name='Tipo de evento'),
        ),
    ]
