# Generated by Django 6.0.5 on 2026-08-01 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacao', '0006_formulacao_custo_animal_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienteformulacao',
            name='origem_custo',
            field=models.CharField(choices=[('CATALOGO', 'Banco de preços do usuário'), ('OVERRIDE_LOCAL', 'Sobrescrito nesta formulação')], default='CATALOGO', max_length=17, verbose_name='Origem do custo'),
        ),
        migrations.CreateModel(
            name='ParametrosViabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_animais', models.PositiveIntegerField(help_text='Cópia editável de Lote.num_animais — não sincronizada.', verbose_name='Número de Animais')),
                ('gmd_esperado_kg', models.FloatField(help_text='Cópia editável de Lote.gmd_esperado — não sincronizada.', verbose_name='GMD (kg) esperado')),
                ('estimativa_permanencia_dias', models.PositiveIntegerField(verbose_name='Estimativa de permanência (dias)')),
                ('peso_entrada_kg', models.FloatField(help_text='Cópia editável de Lote.peso_vivo — não sincronizada.', verbose_name='Peso Vivo Real (Kg) na Entrada')),
                ('cms_percentual_pv', models.FloatField(help_text='Fração 0-1 (ex.: 0.0297 = 2,97%). NÃO é ExigenciaConfigurada.cms_kg — é uma estimativa simplificada só para projeção de consumo/custo ao longo do período de confinamento.', verbose_name='CMS (%) do peso vivo')),
                ('perdas_alimentos_percentual', models.FloatField(default=0.08, help_text='Fração 0-1 (ex.: 0.08 = 8%). Sobra/desperdício no cocho.', verbose_name='Perdas de Alimentos (%)')),
                ('preco_venda_kg_pv', models.FloatField(blank=True, help_text='Preço esperado de venda do animal vivo, por kg de peso vivo.', null=True, verbose_name='Preço de venda (R$/kg de PV)')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField(auto_now=True)),
                ('formulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_viabilidade', to='formulacao.formulacao')),
            ],
            options={
                'verbose_name': 'Parâmetros de Viabilidade',
                'verbose_name_plural': 'Parâmetros de Viabilidade',
            },
        ),
    ]
