# Generated by Django 6.0.5 on 2026-08-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulacao", "0007_alter_ingredienteformulacao_origem_custo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenciaSuplementoValidada",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(db_index=True, max_length=40, unique=True)),
                ("fonte", models.CharField(max_length=200)),
                ("versao_fonte", models.CharField(default="v1", max_length=40)),
                ("origem_arquivo", models.CharField(max_length=255)),
                ("categoria_id_origem", models.CharField(max_length=40)),
                ("categoria", models.CharField(db_index=True, max_length=40)),
                ("fase", models.CharField(db_index=True, max_length=40)),
                ("fase_meses", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("peso_vivo_kg", models.FloatField()),
                ("gmd_kg", models.FloatField()),
                ("cms_kg", models.FloatField()),
                ("pb_requisito_pct", models.FloatField()),
                ("ndt_requisito_pct", models.FloatField()),
                ("ca_requisito_pct", models.FloatField()),
                ("p_requisito_pct", models.FloatField()),
                ("ca_p_requisito", models.FloatField()),
                ("pb_resultado_pct", models.FloatField()),
                ("ndt_resultado_pct", models.FloatField()),
                ("fdn_resultado_pct", models.FloatField()),
                ("ee_resultado_pct", models.FloatField()),
                ("ca_resultado_pct", models.FloatField()),
                ("p_resultado_pct", models.FloatField()),
                ("ca_p_resultado", models.FloatField()),
                ("dieta_ms_pct", models.FloatField()),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("dt_criacao", models.DateTimeField(auto_now_add=True)),
                ("dt_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Referência de suplemento validada",
                "verbose_name_plural": "Referências de suplementos validadas",
                "ordering": ["categoria", "fase", "peso_vivo_kg", "gmd_kg", "codigo"],
            },
        ),
        migrations.AddIndex(
            model_name="referenciasuplementovalidada",
            index=models.Index(fields=["ativo", "categoria", "fase"], name="formulacao__ativo_36b49c_idx"),
        ),
        migrations.CreateModel(
            name="ReferenciaSuplementoIngrediente",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo_origem", models.CharField(max_length=80)),
                ("nome_origem", models.CharField(max_length=200)),
                ("classificacao", models.CharField(max_length=30)),
                ("tipo", models.CharField(max_length=40)),
                ("participacao_pct_ms", models.FloatField()),
                ("ms_pct", models.FloatField()),
                ("pb_pct", models.FloatField()),
                ("ndt_pct", models.FloatField()),
                ("fdn_pct", models.FloatField()),
                ("ee_pct", models.FloatField()),
                ("ca_pct", models.FloatField()),
                ("p_pct", models.FloatField()),
                ("referencia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ingredientes", to="formulacao.referenciasuplementovalidada")),
            ],
            options={
                "verbose_name": "Ingrediente da referência validada",
                "verbose_name_plural": "Ingredientes das referências validadas",
                "ordering": ["referencia", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="referenciasuplementoingrediente",
            constraint=models.UniqueConstraint(fields=("referencia", "codigo_origem"), name="referencia_suplemento_codigo_origem_unico"),
        ),
    ]
