# Generated by Django 6.0.5 on 2026-08-17

from django.db import migrations, models


def preencher_alvos_existentes(apps, schema_editor):
    from django.db.models import Sum

    Formulacao = apps.get_model("formulacao", "Formulacao")
    IngredienteFormulacao = apps.get_model("formulacao", "IngredienteFormulacao")
    EventoFormulacao = apps.get_model("formulacao", "EventoFormulacao")

    for formulacao in Formulacao.objects.all().iterator():
        evento_criacao = (
            EventoFormulacao.objects
            .filter(formulacao_id=formulacao.id, tipo_evento="CRIACAO")
            .order_by("-dt_criacao")
            .first()
        )
        alvo = (evento_criacao.payload or {}).get("percentual_alvo_vol") if evento_criacao else None
        try:
            alvo = float(alvo) if alvo is not None else None
        except (TypeError, ValueError):
            alvo = None

        if alvo is not None and alvo > 1.0:
            alvo /= 100.0
        if alvo is None or not 0.0 <= alvo <= 1.0:
            participacoes = IngredienteFormulacao.objects.filter(
                formulacao_id=formulacao.id
            )
            if participacoes.exists():
                alvo = (
                    participacoes.filter(ingrediente__classificacao="volumoso")
                    .aggregate(soma=Sum("ms_porcent"))["soma"]
                    or 0.0
                ) / 100.0
            else:
                alvo = 0.50

        Formulacao.objects.filter(pk=formulacao.pk).update(
            percentual_alvo_volumoso=alvo
        )


class Migration(migrations.Migration):

    dependencies = [
        ("formulacao", "0008_referencias_suplementos_validadas"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulacao",
            name="percentual_alvo_volumoso",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "Participação total rígida de ingredientes classificados como "
                    "volumoso, armazenada como fração de 0 a 1."
                ),
                null=True,
                verbose_name="Alvo de volumosos (fração da MS)",
            ),
        ),
        migrations.RunPython(preencher_alvos_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="formulacao",
            name="percentual_alvo_volumoso",
            field=models.FloatField(
                default=0.50,
                help_text=(
                    "Participação total rígida de ingredientes classificados como "
                    "volumoso, armazenada como fração de 0 a 1."
                ),
                verbose_name="Alvo de volumosos (fração da MS)",
            ),
        ),
    ]
