# Generated by Django 6.0.5 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulacao", "0009_formulacao_percentual_alvo_volumoso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventoformulacao",
            name="tipo_evento",
            field=models.CharField(
                choices=[
                    ("CRIACAO", "Formulação criada"),
                    ("INGREDIENTE_ADICIONADO", "Ingrediente adicionado"),
                    ("INGREDIENTE_REMOVIDO", "Ingrediente removido"),
                    ("PARTICIPACAO_EDITADA", "Participação editada manualmente"),
                    ("PARTICIPACAO_DESTRAVADA", "Participação destravada"),
                    ("EXIGENCIA_ALTERADA", "Exigência configurada alterada"),
                    ("RECALCULO_SOLICITADO", "Recálculo explícito solicitado"),
                    ("REDISTRIBUICAO_EXECUTADA", "Redistribuição automática executada"),
                    ("PERCENTUAL_VOLUMOSO_ALTERADO", "Alvo de volumosos alterado"),
                    ("VERSAO_RESTAURADA", "Estado restaurado a partir de snapshot"),
                    ("PRECO_ATUALIZADO", "Preço de ingrediente atualizado"),
                ],
                db_index=True,
                max_length=30,
                verbose_name="Tipo de evento",
            ),
        ),
    ]
