# Generated by Django 6.0.5 on 2026-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulacao', '0011_modo_percentual_volumoso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrosviabilidade',
            name='cms_percentual_pv',
            field=models.FloatField(help_text='Armazenado internamente como fração 0-1; a API recebe e devolve percentual 0-100 (ex.: 2,97). NÃO é ExigenciaConfigurada.cms_kg — é uma estimativa simplificada só para projeção de consumo/custo ao longo do período de confinamento.', verbose_name='CMS (%) do peso vivo'),
        ),
        migrations.AlterField(
            model_name='parametrosviabilidade',
            name='estimativa_permanencia_dias',
            field=models.PositiveIntegerField(help_text='Tempo no confinamento.', verbose_name='Estimativa de permanência (dias)'),
        ),
        migrations.AlterField(
            model_name='parametrosviabilidade',
            name='perdas_alimentos_percentual',
            field=models.FloatField(default=0.1, help_text='Armazenado internamente como fração 0-1; a API recebe e devolve percentual 0-100 (ex.: 10). Sobra/desperdício no cocho.', verbose_name='Perdas de Alimentos (%)'),
        ),
    ]
