# Generated by Django 6.0.5 on 2026-05-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propriedade',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='accounts.usuario'),
        ),
    ]
