# Generated by Django 6.0.5 on 2026-06-04 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('volumoso', 'Volumoso'), ('concentrado', 'Concentrado')], db_index=True, max_length=20, verbose_name='Classificação')),
                ('tipo', models.CharField(choices=[('forragens_secas', 'Forragens Secas'), ('forragens_verdes', 'Forragens Verdes'), ('silagens', 'Silagens'), ('energetico', 'Energético'), ('proteico', 'Proteico'), ('mineral', 'Mineral'), ('aditivos', 'Aditivos'), ('outro', 'Outro')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do ingrediente')),
                ('ms', models.FloatField(verbose_name='MS (%)')),
                ('pb', models.FloatField(verbose_name='PB (%)')),
                ('ndt', models.FloatField(verbose_name='NDT (%)')),
                ('fdn', models.FloatField(verbose_name='FDN (%)')),
                ('ee', models.FloatField(verbose_name='EE (%)')),
                ('ca', models.FloatField(verbose_name='Ca (%)')),
                ('p', models.FloatField(verbose_name='P (%)')),
                ('custo_kg', models.FloatField(default=0.0, verbose_name='Custo (R$/kg MN)')),
                ('fonte_valadares', models.BooleanField(db_index=True, default=False, help_text='True = ingrediente da tabela Valadares Filho (2010); False = custom do usuário.', verbose_name='Base Valadares')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_custom', to='accounts.usuario', verbose_name='Usuário (custom)')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['classificacao', 'tipo', 'nome'],
                'indexes': [models.Index(fields=['classificacao', 'tipo'], name='ingrediente_classif_2d0f4f_idx'), models.Index(fields=['fonte_valadares', 'classificacao'], name='ingrediente_fonte_v_167771_idx')],
            },
        ),
    ]
