# Generated by Django 6.0.5 on 2026-07-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingrediente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='limite_max_participacao',
            field=models.FloatField(blank=True, help_text='Percentual máximo (0-100) que este ingrediente pode representar na matéria seca total de uma formulação (ex.: bicarbonato de sódio limitado a 1.5%). Deixe em branco para não aplicar nenhum limite.', null=True, verbose_name='Limite máximo de participação (% MS)'),
        ),
    ]
