# Generated by Django 6.0.5 on 2026-07-27 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('ingrediente', '0002_ingrediente_limite_max_participacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecoIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_anterior', models.FloatField(null=True)),
                ('preco_novo', models.FloatField(null=True)),
                ('origem_alteracao', models.CharField(choices=[('CATALOGO', 'Banco de preços do usuário'), ('FORMULACAO', 'Override local (uma receita)')], max_length=15)),
                ('dt_alteracao', models.DateTimeField(auto_now_add=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='ingrediente.ingrediente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_precos_ingredientes', to='accounts.usuario')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preço',
                'ordering': ['-dt_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='PrecoIngredienteUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_kg_mn', models.FloatField(verbose_name='Preço (R$/kg MN)')),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_usuarios', to='ingrediente.ingrediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precos_ingredientes', to='accounts.usuario')),
            ],
            options={
                'verbose_name': 'Preço de Ingrediente (usuário)',
                'verbose_name_plural': 'Preços de Ingredientes (usuário)',
                'constraints': [models.UniqueConstraint(fields=('usuario', 'ingrediente'), name='unico_preco_por_usuario_ingrediente')],
            },
        ),
    ]
