# Generated by Django 6.0.5 on 2026-05-25 22:17
# pylint: skip-file

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lote', models.CharField(max_length=200)),
                ('raca', models.CharField(blank=True, max_length=100, null=True)),
                ('sistema', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('cordeiro', 'Cordeiro'), ('carneiro', 'Carneiro'), ('ovelha', 'Ovelha')], max_length=20)),
                ('idade', models.CharField(choices=[('ate_4_meses', '0-4 meses'), ('ate_8_meses', '5-8 meses'), ('ate_12_meses', '9-12 meses'), ('mais_12_meses', '13 meses ou mais')], max_length=20)),
                ('fase', models.CharField(choices=[('crescimento', 'Crescimento'), ('manutencao', 'Manutenção'), ('pre_cobricao', 'Pré-cobrição'), ('reproducao', 'Reprodução'), ('gestacao_precoce', 'Gestação'), ('gestacao_tardia', 'Gestação tardia'), ('inicio_lactacao', 'Início da lactação'), ('meio_lactacao', 'Meio da lactação'), ('lactacao_tardia', 'Lactação tardia')], max_length=20)),
                ('tipo_parto', models.PositiveSmallIntegerField(blank=True, choices=[('1', '1 Cordeiro'), ('2', '2 Cordeiros'), ('3', '3 Cordeiros'), ('4', '4 Cordeiros'), ('5', '5 Cordeiros')], null=True)),
                ('dias_fase', models.PositiveIntegerField(blank=True, help_text='Número de dias na fase atual (requerido para fases de gestação e lactação)', null=True)),
                ('peso_vivo', models.FloatField(help_text='Peso vivo médio dos animais do lote (kg)')),
                ('gmd_esperado', models.FloatField(help_text='Ganho médio diário esperado para o lote (kg/dia)')),
                ('num_animais', models.PositiveIntegerField(help_text='Número de animais no lote')),
                ('pv_percentual', models.FloatField(blank=True, help_text='Percentual do peso vivo em relação ao peso vivo ideal (%)', null=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='propriedade.propriedade')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-dt_cadastro'],
            },
        ),
    ]
