# Generated by Django 6.0.5 on 2026-05-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='categoria',
            field=models.CharField(choices=[('cordeiro', 'Cordeiro'), ('carneiro', 'Carneiro'), ('ovelha', 'Ovelha')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='dias_fase',
            field=models.PositiveIntegerField(blank=True, help_text='Número de dias na fase atual (requerido para gestação e lactação).', null=True, verbose_name='Dias na fase'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fase',
            field=models.CharField(choices=[('crescimento', 'Crescimento'), ('manutencao', 'Manutenção'), ('pre_cobricao', 'Pré-cobrição'), ('reproducao', 'Reprodução'), ('gestacao_precoce', 'Gestação precoce'), ('gestacao_tardia', 'Gestação tardia'), ('inicio_lactacao', 'Início da lactação'), ('meio_lactacao', 'Meio da lactação'), ('lactacao_tardia', 'Lactação tardia')], max_length=20, verbose_name='Fase produtiva'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='gmd_esperado',
            field=models.FloatField(verbose_name='GMD esperado (kg/dia)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='idade',
            field=models.CharField(choices=[('ate_4_meses', '0–4 meses'), ('ate_8_meses', '5–8 meses'), ('ate_12_meses', '9–12 meses'), ('mais_12_meses', '13 meses ou mais')], max_length=20, verbose_name='Faixa etária'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='nome_lote',
            field=models.CharField(max_length=200, verbose_name='Nome do lote'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='num_animais',
            field=models.PositiveIntegerField(verbose_name='Número de animais'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='peso_vivo',
            field=models.FloatField(verbose_name='Peso vivo médio (kg)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='pv_percentual',
            field=models.FloatField(blank=True, help_text='Percentual do peso vivo utilizado no cálculo de CMS.', null=True, verbose_name='% Peso vivo'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='raca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='sistema',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema de criação'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipo_parto',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Cordeiro'), (2, '2 Cordeiros'), (3, '3 Cordeiros'), (4, '4 Cordeiros'), (5, '5 Cordeiros')], help_text='Requerido para fases de gestação e lactação.', null=True, verbose_name='Tipo de parto'),
        ),
    ]
