# Generated by Django 6.0.5 on 2026-06-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_alter_lote_categoria_alter_lote_dias_fase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='idade',
        ),
        migrations.AlterField(
            model_name='lote',
            name='categoria',
            field=models.CharField(choices=[('cordeiros_4_meses', 'Cordeiros(as) 4 meses'), ('cordeiros_8_meses', 'Cordeiros(as) 8 meses'), ('carneiro_4_meses', 'Carneiro 4 meses'), ('carneiro_8_meses', 'Carneiro 8 meses'), ('carneiros', 'Carneiros'), ('ovelhas', 'Ovelhas')], max_length=20, verbose_name='Categoria'),
        ),
    ]
