# Generated by Django 6.0.5 on 2026-07-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0003_remove_lote_idade_alter_lote_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='dias_fase',
        ),
    ]
