# Generated by Django 6.0.5 on 2026-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_remove_lote_dias_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='producao_leite_kg_dia',
            field=models.FloatField(blank=True, null=True, verbose_name='Produção de leite (kg/dia)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='pv_nascer_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso vivo ao nascer (kg)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='gmd_esperado',
            field=models.FloatField(verbose_name='Ganho médio por dia esperado (kg/dia)'),
        ),
    ]
