# Generated by Django 6.0.5 on 2026-05-25 22:17
# pylint: skip-file

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('proprietario', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=255)),
                ('localidade', models.CharField(max_length=255)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propriedades',
                'ordering': ['-dt_cadastro'],
            },
        ),
    ]
