# Generated by Django 6.0.5 on 2026-07-14 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propriedade', '0002_alter_propriedade_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propriedade',
            options={'ordering': ['-dt_cadastro'], 'verbose_name': 'Propriedade', 'verbose_name_plural': 'Propriedades'},
        ),
    ]
