# Generated by Django 6.0.5 on 2026-06-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExigenciaNRC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('cordeiros_4_meses', 'Cordeiros(as) 4 meses'), ('cordeiros_8_meses', 'Cordeiros(as) 8 meses'), ('carneiro_4_meses', 'Carneiro 4 meses'), ('carneiro_8_meses', 'Carneiro 8 meses'), ('carneiros', 'Carneiros'), ('ovelhas', 'Ovelhas')], db_index=True, max_length=20, verbose_name='Categoria')),
                ('fase', models.CharField(choices=[('crescimento', 'Crescimento'), ('manutencao', 'Manutenção'), ('pre_cobricao', 'Pré-cobrição'), ('reproducao', 'Reprodução'), ('gestacao_precoce', 'Gestação precoce'), ('gestacao_tardia', 'Gestação tardia'), ('inicio_lactacao', 'Início da lactação'), ('meio_lactacao', 'Meio da lactação'), ('lactacao_tardia', 'Lactação tardia')], db_index=True, max_length=20, verbose_name='Fase produtiva')),
                ('pv_kg', models.FloatField(db_index=True, verbose_name='Peso vivo (kg)')),
                ('tipo_parto', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 Cordeiro'), (2, '2 Cordeiros'), (3, '3 Cordeiros'), (4, '4 Cordeiros'), (5, '5 Cordeiros')], help_text='Requerido para fases de gestação e lactação.', null=True, verbose_name='Tipo de parto')),
                ('dias_fase', models.PositiveIntegerField(blank=True, help_text='Dias dentro da fase (gestação/lactação).', null=True, verbose_name='Dias na fase')),
                ('pv_nascer_kg', models.FloatField(blank=True, null=True, verbose_name='PV ao nascer (kg)')),
                ('producao_leite_kg_dia', models.FloatField(blank=True, null=True, verbose_name='Produção de leite (kg/dia)')),
                ('gmd_kg', models.FloatField(blank=True, db_index=True, null=True, verbose_name='GMD (kg/dia)')),
                ('pv_percentual', models.FloatField(blank=True, null=True, verbose_name='% PV')),
                ('cms_kg', models.FloatField(blank=True, null=True, verbose_name='CMS (kg/dia)')),
                ('pb_g', models.FloatField(blank=True, null=True, verbose_name='PB (g)')),
                ('pb_percentual', models.FloatField(blank=True, null=True, verbose_name='PB (%)')),
                ('ndt_kg', models.FloatField(blank=True, null=True, verbose_name='NDT (kg)')),
                ('ndt_percentual', models.FloatField(blank=True, null=True, verbose_name='NDT (%)')),
                ('fdn_kg', models.FloatField(blank=True, null=True, verbose_name='FDN (kg)')),
                ('fdn_percentual', models.FloatField(blank=True, null=True, verbose_name='FDN (%)')),
                ('ee_kg', models.FloatField(blank=True, null=True, verbose_name='EE (kg)')),
                ('ee_percentual', models.FloatField(blank=True, null=True, verbose_name='EE (%)')),
                ('ca_g', models.FloatField(blank=True, null=True, verbose_name='Ca (g)')),
                ('ca_percentual', models.FloatField(blank=True, null=True, verbose_name='Ca (%)')),
                ('p_g', models.FloatField(blank=True, null=True, verbose_name='P (g)')),
                ('p_percentual', models.FloatField(blank=True, null=True, verbose_name='P (%)')),
                ('ca_p_percentual', models.FloatField(blank=True, null=True, verbose_name='Relação Ca:P')),
            ],
            options={
                'verbose_name': 'Exigência Nutricional (NRC)',
                'verbose_name_plural': 'Exigências Nutricionais (NRC)',
                'ordering': ['categoria', 'fase', 'pv_kg', 'gmd_kg'],
                'indexes': [models.Index(fields=['categoria', 'fase', 'pv_kg'], name='exigencia_n_categor_75193e_idx')],
            },
        ),
    ]
