# Generated by Django 6.0.5 on 2026-07-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exigencia_nrc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exigencianrc',
            name='dias_fase',
        ),
    ]
